<?php
/**
 * 1997-2015 Quadra Informatique
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0) that is available
 * through the world-wide-web at this URL: http://www.opensource.org/licenses/OSL-3.0
 * If you are unable to obtain it through the world-wide-web, please send an email
 * to modules@quadra-informatique.fr so we can send you a copy immediately.
 *
 * @author Quadra Informatique <modules@quadra-informatique.fr>
 * @copyright 1997-2015 Quadra Informatique
 * @license http://www.opensource.org/licenses/OSL-3.0 Open Software License (OSL 3.0)
 */
?>
<?php $_code = $this->getMethodCode() ?>
<ul class="form-list">
    <li>
        <div class="atos-logo">
            <img src="<?php echo Mage::getBaseUrl('media') . 'atos/logo/AURORE.gif' ?>" alt="AURORE" />
        </div>
    </li>
</ul>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none">
    <li><?php echo $this->__('You will be redirected to the payment server after the finalization of your order.') ?></li>
    <li>
        <strong><?php echo $this->__('To pay with %s, we need your birth date. Please, check it.', $this->getMethod()->getTitle()); ?></strong>
    </li>
    <li>
        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat($_code . ':%s')->setFieldNameFormat($_code . '[%s]')->toHtml() ?>
    </li>
    <script type="text/javascript">
        if ($('payment-buttons-container')) {
            var button = $('payment-buttons-container').down('button');
            var atosAuoreMethod = $('p_method_<?php echo $_code ?>');
            if (button && atosAuoreMethod) {
                Event.observe(button, 'click', function() {
                    if (atosAuoreMethod.checked === true) {
                        params = {
                            dob: $('<?php echo $_code ?>:dob').value
                        };
                        new Ajax.Request('<?php echo Mage::getUrl('atos/payment/saveAuroreDob', array('_secure' => true)); ?>', {
                            method: 'post',
                            parameters: params
                        });
                    }
                });
            }
        }
    </script>
</ul>
